import{readFile,writeFile,mkdir,rename}from'node:fs/promises';import{validate,easternDate}from'./model.mjs';import{revalidateOffers}from'./verify.mjs';import{requestText}from'./outbound.mjs';
// Conservative discovery: untrusted remote text is data, never executable instructions.
const data=validate(JSON.parse(await readFile('data/deals.json','utf8'))),date=easternDate(),report={ranAt:new Date().toISOString(),checked:[],review:[],failures:[],candidates:[]};
const rules=JSON.parse(await readFile('data/verification.json','utf8'));
const allowedHosts=JSON.parse(await readFile('data/source-hosts.json','utf8'));
if(!Array.isArray(allowedHosts)||allowedHosts.some(host=>typeof host!=='string'||!host||new URL('https://'+host).hostname!==host))throw Error('Invalid approved source host list');
function plain(html){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&#(x[0-9a-f]+|\d+);/gi,(_,value)=>{const n=value[0].toLowerCase()==='x'?parseInt(value.slice(1),16):Number(value);return n>0&&n<=0x10ffff?String.fromCodePoint(n):' ';}).replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&rsquo;/g,'’').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();}
let successes=0;for(const url of [...new Set(data.deals.map(d=>d.sourceUrl))]){const records=data.deals.filter(d=>d.sourceUrl===url);try{const response=await requestText(url,{allowedHosts,headers:{'User-Agent':'LoudounDealsSourceChecker/1.0'}});if(response.contentType.split(';')[0].trim().toLowerCase()!=='text/html'){report.review.push({url,reason:'Non-HTML source requires manual review; freshness unchanged.'});continue;}const html=response.text;const text=plain(html);if(text.length<150)throw Error('Empty or blocked page');successes++;revalidateOffers(records,text,date,report,rules);
 // Discover additional specials pages only on the same restaurant origin.
 const links=[...html.matchAll(/href=["']([^"']+)["']/gi)].map(m=>m[1]);for(const href of links){try{const link=new URL(href,url);if(link.origin===new URL(url).origin&&/special|happy-hour|promotion|kids-eat|deal/i.test(link.pathname)&&!data.deals.some(d=>d.sourceUrl===link.href)&&!report.candidates.some(c=>c.url===link.href))report.candidates.push({url:link.href,restaurant:records[0].restaurant,town:records[0].town,status:'needs-review'});}catch{}}
 }catch(error){report.failures.push({url,error:error.message});}}
// Optional broader discovery. Configure a Brave Search API key in CI secrets.
if(process.env.BRAVE_SEARCH_API_KEY){try{const q='Loudoun County Ashburn Leesburg Sterling restaurant meal deals specials';const response=await requestText('https://api.search.brave.com/res/v1/web/search?q='+encodeURIComponent(q)+'&count=20',{allowedHosts:['api.search.brave.com'],headers:{'X-Subscription-Token':process.env.BRAVE_SEARCH_API_KEY,Accept:'application/json'},maxBytes:1_000_000});let payload;try{payload=JSON.parse(response.text);}catch{throw Error('Invalid search JSON');}for(const result of payload.web?.results||[])report.candidates.push({title:result.title,url:result.url,description:result.description,status:'needs-review'});}catch(error){report.failures.push({source:'discovery',error:error.message});}}
if(report.checked.length)data.updatedAt=new Date().toISOString();validate(data);await mkdir('reports',{recursive:true});await writeFile('reports/latest.json',JSON.stringify(report,null,2));await writeFile('data/deals.json.tmp',JSON.stringify(data,null,2)+'\n');await rename('data/deals.json.tmp','data/deals.json');console.log(JSON.stringify({checked:report.checked.length,review:report.review.length,candidates:report.candidates.length,failures:report.failures.length}));if(!successes)process.exitCode=1;
